import Head from 'next/head'

import { useEffect, useState } from 'react'
import axios from 'axios'
import cartIcon from 'public/Vector.svg'
import { IProduct } from '@/interface/product'
import Card from '@/components/Card'
import { GlobalStyle } from '@/styles/style'
import Sidebar from '@/components/Sidebar'
import { useDispatch, useSelector } from 'react-redux'
import { OpenSidebar } from '@/context/features/navbar'
import {
  Header,
  TituloContainer,
  Titulo,
  SubTtitulo,
  DivCart,
  StyledImage,
  CartItens,
  Body,
  CardContainer,
  Footer,
  TextoDoFooter
} from './../styles/indexStyle'
import { RootState } from '@/context/store'

export default function Home() {

  const [ListaDeProdutos, setListadeProdutos] = useState<IProduct[]>([])

  useEffect(() => {
    axios.get('https://mks-challenge-api-frontend.herokuapp.com/api/v1/products?page=1&rows=8&sortBy=id&orderBy=DESC')
      .then(res => setListadeProdutos(res.data.products))
  }, [])

  const dispatch = useDispatch()
  const CartItensArr = useSelector((state: RootState) => state.cart)
  const CartItensCounter = useSelector((state: RootState) => state.cart.length)


  return (
    <>
      <GlobalStyle />
      <Head>
        <title>MKS sistemas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <Header>
        <TituloContainer>
          <Titulo>
            MKS
          </Titulo>
          <SubTtitulo>
            Sistemas
          </SubTtitulo>
        </TituloContainer>
        <DivCart onClick={() => dispatch(OpenSidebar())} >
          <StyledImage src={cartIcon} alt='Carrinho' />
          <CartItens> {CartItensCounter} </CartItens>
        </DivCart>
      </Header>
      <Body>
        <CardContainer>
          {ListaDeProdutos.map(item => (
            <Card photo={item.photo} key={item.id} brand={item.brand} description={item.description} id={item.id} name={item.name} price={item.price} />
          ))}
        </CardContainer>
      </Body>
      <Footer>
        <TextoDoFooter>MKS sistemas © Todos os direitos reservados</TextoDoFooter>
      </Footer>
    </>
  )
}
