import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import axios from 'axios'
import styled from 'styled-components'
import cartIcon from 'public/Vector.svg'
import { IProduct } from '@/interface/poroduct'
import Card from '@/components/Card'
import { GlobalStyle } from '@/styles/style'
import Sidebar from '@/components/Sidebar'
import { useDispatch } from 'react-redux'
import { CloseSidebar, OpenSidebar } from '@/context/features/navbar'


export default function Home() {

  const [ListaDeProdutos, setListadeProdutos] = useState<IProduct[]>([])

  useEffect(() => {
    axios.get('https://mks-challenge-api-frontend.herokuapp.com/api/v1/products?page=1&rows=8&sortBy=id&orderBy=DESC')
      .then(res => setListadeProdutos(res.data.products))
  }, [])

  const dispatch = useDispatch()

  const Footer = styled.footer`
  background: #EEEEEE;
  `
  const TextoDoFooter = styled.h1`
  font-size: 12px;
  font-weight: 400;
  text-align: center;
  color: #000000;
  `;

  const Header = styled.nav`
  background-color: #0F52BA;
  width: 100%;
  min-height: 100px;
  padding-right: 88px;
  padding-left: 65px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  `

  const Titulo = styled.h1`
  font-size: 40px;
  font-weight: 600;
  color: #FFFFFF;
  `

  const SubTtitulo = styled.h2`
  font-size: 20px;
  font-weight: 300;
  position: relative;
  bottom: 3px;
  color: #FFFFFF;
  `

  const TituloContainer = styled.div`
  display: flex;
  align-items: baseline;
  gap: 0.75rem;
  `

  const DivCart = styled.button` 
  display: flex;
  background-color: white;
  width: 90px;
  height: 45px;
  gap: 1rem;
  border-radius: 8px;
  justify-content: center;
  align-items: center;
  cursor: pointer;
  border: none;
  `

  const CartItens = styled.div` 
  color: #000000;
  font-weight: bold;
  font-size: 16px;
  `
  const StyledImage = styled(Image)`
    width: 19px;
    height: 19px;
  `

  const Body = styled.main`
  min-height: calc(100vh - 115px);
  display: flex;
  justify-content: center;
  align-items: center;
  `

  const CardContainer = styled.section`
  display: grid;
  column-gap: 31px;
  row-gap: 31px;
  grid-template-columns: repeat(4, 190px);
  `

  return (
    <>
      <GlobalStyle />
      <Head>
        <title>MKS sistemas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <Header>
        <TituloContainer>
          <Titulo>
            MKS
          </Titulo>
          <SubTtitulo>
            Sistemas
          </SubTtitulo>
        </TituloContainer>
        <DivCart onClick={() => dispatch(OpenSidebar())} >
          <StyledImage src={cartIcon} alt='Carrinho' />
          <CartItens> 0 </CartItens>
        </DivCart>
      </Header>
      <Body>
        <CardContainer>
          {ListaDeProdutos.map(item => (
            <Card photo={item.photo} key={item.id} brand={item.brand} description={item.description} id={item.id} name={item.name} price={item.price} />
          ))}
        </CardContainer>
      </Body>
      <Footer>
        <TextoDoFooter>MKS sistemas © Todos os direitos reservados</TextoDoFooter>
      </Footer>
    </>
  )
}
